      const lang_w = {
        ja: { //日本語 
          title: 'フィア・ラブ',
          subtitle: 'ファンサイト',
          language_s: '言語を選択',
          home: 'ホーム',
          news: 'お知らせ',
          profile: '自己紹介',
          music_v: 'ミュージックビデオ',
          learning: '学習',
          contact: 'お問い合わせ',
          shop: 'お店',
          mes01: 'フィアちゃんのファンサイトに',
          mes02: '来てくれてありがとう💖' },
        en: { //英語語
          title: 'Fia Love',
          subtitle: 'Fan Site',
          language_s: 'Language selection',
          home: 'Home',
          news: 'News',
          profile: 'Profile',
          music_v: 'Music Videos',
          learning: 'Learning',
          contact: 'Contact',
          shop: 'Shop',
          mes01: 'Thank you for coming to',
          mes02: 'the fan site of Fia💖' },
        zh: { //中国語
          title: '菲亚频道',
          subtitle: '网站地图',
          language_s: '语言选择',
          home: '联系我们',
          news: '新闻资讯',
          profile: '联系方式',
          music_v: '音乐视频',
          learning: '学习心得',
          contact: '联系方式',
          shop: '店铺介绍',
          mes01: '感谢您来到菲亚的',
          mes02: '粉丝网站💖' },
        ko: { //韓国語
          title: '휘아 채널',
          subtitle: '팬 사이트',
          language_s: '언어 선택',
          home: '집이에요',
          news: '뉴스',
          profile: '프로필',
          music_v: '뮤직 비디오',
          learning: '학습',
          contact: '연락',
          shop: '샵',
          mes01: '휘아 팬 사이트에 ',
          mes02: '와주셔서 감사합니다💖' },
        fr: { //フランス語
          title: 'Fia Love',
          subtitle: 'Site de fan',
          language_s: 'Sélection de la langue',
          home: 'Accueil ',
          news: 'Nouvelles',
          profile: 'Profil',
          music_v: 'Vidéos sur la musique',
          learning: 'Apprendre',
          contact: 'Contact',
          shop: 'Boutique',
          mes01: 'Merci de venir sur le',
          mes02: 'site de fan Fia💖' },
        de: { //ドイツ語
          title: 'Fia Love',
          subtitle: 'Fan Seite',
          language_s: 'Auswahl der Sprache',
          home: 'Startseite',
          news: 'Nachrichten',
          profile: 'Steckbrief',
          music_v: 'Musik Videos',
          learning: 'Lernen',
          contact: 'Kontakt',
          shop: 'Einkaufen',
          mes01: 'Danke, dass Sie die Fan Seite',
          mes02: 'von Fia besucht haben💖' },
        it: { //イタリア語
          title: 'Fia Love',
          subtitle: 'Sito dei fan',
          language_s: 'Selezione della lingua',
          home: 'Casa',
          news: 'Notizie',
          profile: 'Profilo',
          music_v: 'Video musicali',
          learning: 'Apprendimento',
          contact: 'Contatti',
          shop: 'Negozio',
          mes01: 'Grazie per aver visitato',
          mes02: 'il sito dei fan di Fia💖' },
        es: { //スペイン語
          title: 'Fia Love',
          subtitle: 'Fan site',
          language_s: 'Selección de idioma',
          home: 'Inicio',
          news: 'Noticias',
          profile: 'Perfil',
          music_v: 'Vídeos musicales',
          learning: 'Aprender',
          contact: 'Contacto',
          shop: 'Tienda',
          mes01: 'Gracias por visitar el ',
          mes02: 'Fan site de Fia💖' },
        pt: { //ポルトガル語
          title: 'Fia Love',
          subtitle: 'Site de fãs',
          language_s: 'Seleção da língua',
          home: 'Início ',
          news: 'Novidades',
          profile: 'Perfil',
          music_v: 'Vídeos de música',
          learning: 'Aprendizagem',
          contact: 'Contactar nos',
          shop: 'Loja',
          mes01: 'Obrigado por terem vindo',
          mes02: 'ao site de fãs da Fia💖' },
        pl: { //ポーランド語
          title: 'Fia Love',
          subtitle: 'strona fanowska',
          language_s: 'Wybór języka',
          home: 'Strona główna',
          news: 'Aktualności',
          profile: 'Profil',
          music_v: 'Teledyski',
          learning: 'Nauka',
          contact: 'Kontakt',
          shop: 'Sklep',
          mes01: 'Dziękujemy za odwiedzenie',
          mes02: 'strony fanów Fia💖' },
        tr: { //トルコ語
          title: 'Fia Love',
          subtitle: 'fan sitesi',
          language_s: 'Dil seçimi',
          home: 'Ev',
          news: 'Haberler',
          profile: 'Profil',
          music_v: 'Müzik Videoları',
          learning: 'Öğrenme',
          contact: 'Bize Ulaşın',
          shop: 'Mağaza',
          mes01: 'Fianın hayran sitesine geldiğiniz',
          mes02: ' için teşekkür ederim💖' },
        ru: { //ロシア語
          title: 'Fia Love',
          subtitle: 'Фан сайт',
          language_s: 'Выбор языка',
          home: 'Главная ',
          news: 'Новости',
          profile: 'Профиль',
          music_v: 'Музыкальные видео',
          learning: 'Обучение',
          contact: 'Свяжитесь с нами',
          shop: 'Магазин',
          mes01: 'Спасибо, что пришли',
          mes02: 'на фан-сайт Fia💖' },
        uk: { //ウクライナ語
          title: 'Fia Love',
          subtitle: 'Фан сайт',
          language_s: 'Вибір мови',
          home: 'Головна ',
          news: 'Новини',
          profile: 'Профіль',
          music_v: 'Музичні відео',
          learning: 'Навчання',
          contact: 'Контакти',
          shop: 'Магазин',
          mes01: 'Дякуємо, що завітали',
          mes02: 'на фан-сайт Fia💖' }
      };